using System.Collections.Generic;

namespace xAPI.Registry {
    /// <summary>
    /// Provides 3 items of the xAPI_Activities of the context exerciseGenerator as public properties.
    /// </summary>
    public sealed class xAPI_Activities_ExerciseGenerator : xAPI_Activities {
        /// <summary>
        /// The "AusgabenGeneratorInfrastruktur", developed at the Learning Technologies Research Group at RWTH Aachen, serving as a provider for different exercise generators.
        /// URI: https://xapi.elearn.rwth-aachen.de/definitions/exerciseGenerator/activities/agi
        /// </summary>
        public readonly xAPI_Activity agi = new xAPI_Activity(
            context: "exerciseGenerator",
            key: "agi",
            names: new Dictionary<string, string> {
                ["en-US"] = "AGI",
                ["de-DE"] = "AGI" },
            descriptions: new Dictionary<string, string> {
                ["en-US"] = "The \"AusgabenGeneratorInfrastruktur\", developed at the Learning Technologies Research Group at RWTH Aachen, serving as a provider for different exercise generators.",
                ["de-DE"] = "Die AufgabenGeneratorInfrastruktur, die am Lehr- und Forschungsgebiet Lerntechnologien an der RWTH Aachen entwickelt wird und verschiedene Aufgabengeneratoren bereitstellt." });

        /// <summary>
        /// An exercise, generated by an exercise generator.
        /// URI: https://xapi.elearn.rwth-aachen.de/definitions/exerciseGenerator/activities/exercise
        /// </summary>
        public readonly xAPI_Activity exercise = new xAPI_Activity(
            context: "exerciseGenerator",
            key: "exercise",
            names: new Dictionary<string, string> {
                ["en-US"] = "Exercise",
                ["de-DE"] = "Aufgabe" },
            descriptions: new Dictionary<string, string> {
                ["en-US"] = "An exercise, generated by an exercise generator.",
                ["de-DE"] = "Eine Aufgabe, die von einem Aufgabengenerator generiert wurde." });

        /// <summary>
        /// An exercise generator.
        /// URI: https://xapi.elearn.rwth-aachen.de/definitions/exerciseGenerator/activities/generator
        /// </summary>
        public readonly xAPI_Activity generator = new xAPI_Activity(
            context: "exerciseGenerator",
            key: "generator",
            names: new Dictionary<string, string> {
                ["en-US"] = "Generator",
                ["de-DE"] = "Generator" },
            descriptions: new Dictionary<string, string> {
                ["en-US"] = "An exercise generator.",
                ["de-DE"] = "Ein Aufgabengenerator." });

        public xAPI_Activities_ExerciseGenerator() 
            : base("exerciseGenerator") {
        }
    }
}